from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import os
import openai
from openai import OpenAIError
import httpx
import asyncio
import json

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

openai.api_key = os.getenv("OPENAI_API_KEY")

# n8n Webhook URL - KORRIGIERT!
N8N_WEBHOOK_URL = "https://primary-production-77f62.up.railway.app/webhook-test/country-report"

@app.get("/")
async def root():
    return {"status": "API is running"}

@app.get("/api/generate")
async def generate(country: str):
    try:
        async with httpx.AsyncClient() as client:
            try:
                n8n_response = await client.post(
                    N8N_WEBHOOK_URL,
                    json={"country": country},
                    timeout=60.0
                )
                
                if n8n_response.status_code == 200:
                    n8n_data = n8n_response.text
                    
                    if n8n_data.strip().startswith('<!DOCTYPE html') or n8n_data.strip().startswith('<html'):
                        return {"html": n8n_data}
                    
                    try:
                        json_data = json.loads(n8n_data)
                        if "html" in json_data:
                            return {"html": json_data["html"]}
                        else:
                            return {"content": json.dumps(json_data, indent=2)}
                    except json.JSONDecodeError:
                        return {"content": n8n_data}
                
            except httpx.TimeoutException:
                pass
            except Exception as e:
                print(f"n8n error: {e}")
        
        # OpenAI Fallback
        prompt = f"Create a comprehensive market report for {country}. Include economic indicators, trade data, and business opportunities."

        response = openai.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are an expert market analyst."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=1000,
            temperature=0.7
        )
        
        ai_text = response.choices[0].message.content
        formatted_html = f"""
        <div class="max-w-4xl mx-auto p-6">
            <div class="bg-white rounded-lg shadow-lg p-8">
                <h1 class="text-2xl font-bold mb-6 text-center">📊 {country} Market Report</h1>
                <div class="bg-orange-50 p-4 rounded mb-6">
                    <p class="text-sm">⚠️ Generated by OpenAI (n8n fallback)</p>
                </div>
                <div class="prose max-w-none">
                    {ai_text.replace('\n\n', '</p><p>').replace('**', '<strong>').replace('**', '</strong>')}
                </div>
            </div>
        </div>
        """
        
        return {"html": formatted_html}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
async def health_check():
    return {"status": "healthy", "n8n_url": N8N_WEBHOOK_URL}
